"""baseline

Revision ID: 9e871544cc83
Revises: 
Create Date: 2026-06-24 10:46:34.805505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e871544cc83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quotes', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quotes', 'technician_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'quote_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('technician_categories', 'technician_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('technician_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('technician_work_zones', 'technician_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('technician_work_zones', 'neighborhood_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technician_work_zones', 'neighborhood_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('technician_work_zones', 'technician_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('technician_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('technician_categories', 'technician_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'quote_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quotes', 'technician_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quotes', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
